import type { PipeSize, PipeMaterial, PipeServiceType, JointType, FittingType } from '../../types';

export const PIPE_SIZES: PipeSize[] = [
  { nominal: '3/8"', nominalInches: 0.375, displayLabel: '3/8"' },
  { nominal: '1/2"', nominalInches: 0.5, displayLabel: '1/2"' },
  { nominal: '3/4"', nominalInches: 0.75, displayLabel: '3/4"' },
  { nominal: '1"', nominalInches: 1.0, displayLabel: '1"' },
  { nominal: '1-1/4"', nominalInches: 1.25, displayLabel: '1-1/4"' },
  { nominal: '1-1/2"', nominalInches: 1.5, displayLabel: '1-1/2"' },
  { nominal: '2"', nominalInches: 2.0, displayLabel: '2"' },
  { nominal: '2-1/2"', nominalInches: 2.5, displayLabel: '2-1/2"' },
  { nominal: '3"', nominalInches: 3.0, displayLabel: '3"' },
  { nominal: '4"', nominalInches: 4.0, displayLabel: '4"' },
  { nominal: '6"', nominalInches: 6.0, displayLabel: '6"' },
  { nominal: '8"', nominalInches: 8.0, displayLabel: '8"' },
  { nominal: '10"', nominalInches: 10.0, displayLabel: '10"' },
  { nominal: '12"', nominalInches: 12.0, displayLabel: '12"' },
  { nominal: '14"', nominalInches: 14.0, displayLabel: '14"' },
  { nominal: '16"', nominalInches: 16.0, displayLabel: '16"' },
  { nominal: '18"', nominalInches: 18.0, displayLabel: '18"' },
  { nominal: '20"', nominalInches: 20.0, displayLabel: '20"' },
  { nominal: '24"', nominalInches: 24.0, displayLabel: '24"' },
  { nominal: '30"', nominalInches: 30.0, displayLabel: '30"' },
  { nominal: '36"', nominalInches: 36.0, displayLabel: '36"' },
];

export const MATERIAL_LABELS: Record<PipeMaterial, string> = {
  copper_type_l: 'Copper Type L',
  copper_type_m: 'Copper Type M',
  copper_type_k: 'Copper Type K',
  black_steel: 'Black Steel',
  galvanized_steel: 'Galvanized Steel',
  stainless_steel: 'Stainless Steel',
  pvc_sch40: 'PVC Sch 40',
  pvc_sch80: 'PVC Sch 80',
  cpvc: 'CPVC',
  cast_iron: 'Cast Iron',
  ductile_iron: 'Ductile Iron',
  pex: 'PEX',
  polypropylene: 'Polypropylene',
  carbon_steel: 'Carbon Steel',
};

export const SERVICE_TYPE_LABELS: Record<PipeServiceType, string> = {
  heating_water: 'Heating Water',
  chilled_water: 'Chilled Water',
  condenser_water: 'Condenser Water',
  refrigerant_liquid: 'Refrigerant Liquid',
  refrigerant_suction: 'Refrigerant Suction',
  refrigerant_hot_gas: 'Refrigerant Hot Gas',
  condensate: 'Condensate',
  steam: 'Steam',
  natural_gas: 'Natural Gas',
  fuel_oil: 'Fuel Oil',
  domestic_hot: 'Domestic Hot Water',
  domestic_cold: 'Domestic Cold Water',
  other: 'Other',
};

export const JOINT_TYPE_LABELS: Record<JointType, string> = {
  soldered_9505: '95/5 Soldered',
  soldered_5050: '50/50 Soldered',
  brazed: 'Brazed',
  welded: 'Welded',
  threaded: 'Threaded',
  grooved: 'Grooved',
  press_fit: 'Press Fit',
  solvent_weld: 'Solvent Weld',
  flanged: 'Flanged',
  compression: 'Compression',
  push_fit: 'Push Fit',
  victaulic: 'Victaulic',
};

export const FITTING_TYPE_LABELS: Record<FittingType, string> = {
  elbow_90: '90° Elbow',
  elbow_45: '45° Elbow',
  tee: 'Tee',
  reducer: 'Reducer',
  coupling: 'Coupling',
  cap: 'Cap',
  union: 'Union',
  flange: 'Flange',
  fishmouth: 'Fishmouth',
};

export const PIPE_SIZES_EXTENDED: PipeSize[] = [
  { nominal: '1/8"', nominalInches: 0.125, displayLabel: '1/8"' },
  { nominal: '1/4"', nominalInches: 0.25, displayLabel: '1/4"' },
  { nominal: '3/8"', nominalInches: 0.375, displayLabel: '3/8"' },
  { nominal: '1/2"', nominalInches: 0.5, displayLabel: '1/2"' },
  { nominal: '5/8"', nominalInches: 0.625, displayLabel: '5/8"' },
  { nominal: '3/4"', nominalInches: 0.75, displayLabel: '3/4"' },
  { nominal: '7/8"', nominalInches: 0.875, displayLabel: '7/8"' },
  { nominal: '1"', nominalInches: 1.0, displayLabel: '1"' },
  { nominal: '1-1/4"', nominalInches: 1.25, displayLabel: '1-1/4"' },
  { nominal: '1-1/2"', nominalInches: 1.5, displayLabel: '1-1/2"' },
  { nominal: '2"', nominalInches: 2.0, displayLabel: '2"' },
  { nominal: '2-1/2"', nominalInches: 2.5, displayLabel: '2-1/2"' },
  { nominal: '3"', nominalInches: 3.0, displayLabel: '3"' },
  { nominal: '3-1/2"', nominalInches: 3.5, displayLabel: '3-1/2"' },
  { nominal: '4"', nominalInches: 4.0, displayLabel: '4"' },
  { nominal: '5"', nominalInches: 5.0, displayLabel: '5"' },
  { nominal: '6"', nominalInches: 6.0, displayLabel: '6"' },
  { nominal: '8"', nominalInches: 8.0, displayLabel: '8"' },
  { nominal: '10"', nominalInches: 10.0, displayLabel: '10"' },
  { nominal: '12"', nominalInches: 12.0, displayLabel: '12"' },
  { nominal: '14"', nominalInches: 14.0, displayLabel: '14"' },
  { nominal: '16"', nominalInches: 16.0, displayLabel: '16"' },
  { nominal: '18"', nominalInches: 18.0, displayLabel: '18"' },
  { nominal: '20"', nominalInches: 20.0, displayLabel: '20"' },
  { nominal: '22"', nominalInches: 22.0, displayLabel: '22"' },
  { nominal: '24"', nominalInches: 24.0, displayLabel: '24"' },
  { nominal: '26"', nominalInches: 26.0, displayLabel: '26"' },
  { nominal: '28"', nominalInches: 28.0, displayLabel: '28"' },
  { nominal: '30"', nominalInches: 30.0, displayLabel: '30"' },
  { nominal: '32"', nominalInches: 32.0, displayLabel: '32"' },
  { nominal: '34"', nominalInches: 34.0, displayLabel: '34"' },
  { nominal: '36"', nominalInches: 36.0, displayLabel: '36"' },
  { nominal: '42"', nominalInches: 42.0, displayLabel: '42"' },
  { nominal: '48"', nominalInches: 48.0, displayLabel: '48"' },
  { nominal: '54"', nominalInches: 54.0, displayLabel: '54"' },
  { nominal: '60"', nominalInches: 60.0, displayLabel: '60"' },
];

export const SERVICE_TYPE_COLORS: Record<PipeServiceType, string> = {
  heating_water: '#ef4444',
  chilled_water: '#06b6d4',
  condenser_water: '#14b8a6',
  refrigerant_liquid: '#ec4899',
  refrigerant_suction: '#f472b6',
  refrigerant_hot_gas: '#f97316',
  condensate: '#84cc16',
  steam: '#f97316',
  natural_gas: '#eab308',
  fuel_oil: '#a3a3a3',
  domestic_hot: '#dc2626',
  domestic_cold: '#2563eb',
  other: '#10b981',
};
