import * as XLSX from 'xlsx';
import { format } from 'date-fns';

interface DiffMeta {
  projectName: string;
  projectNumber?: string | null;
  fromVersionLabel: string;
  toVersionLabel: string;
  fromUploadedAt?: string | null;
  toUploadedAt?: string | null;
  generatedBy?: string | null;
}

interface DiffCounts {
  added: number;
  removed: number;
  changed: number;
}

interface DiffRowChanged {
  activity_id: string | null;
  name: string | null;
  is_mechanical?: boolean;
  diffs: Record<string, any>;
}

interface DiffRowSimple {
  activity_id: string | null;
  activity_name?: string | null;
  name?: string | null;
  is_mechanical?: boolean;
  start_date?: string | null;
  finish_date?: string | null;
}

interface ExportOptions {
  meta: DiffMeta;
  counts: DiffCounts;
  changed: DiffRowChanged[];
  added: DiffRowSimple[];
  removed: DiffRowSimple[];
  fileName: string;
}

function fmtDate(s: string | null | undefined): string {
  if (!s) return '';
  const iso = s.length >= 10 ? s.slice(0, 10) : s;
  const d = new Date(iso + 'T00:00:00');
  if (Number.isNaN(d.getTime())) return String(s);
  return format(d, 'MMM d, yyyy');
}

function days(n: number): string {
  return `${Math.abs(n)} day${Math.abs(n) === 1 ? '' : 's'}`;
}

function fieldVerdict(k: string, v: any): { field: string; verdict: string; from: string; to: string } {
  if (k === 'start' || k === 'finish') {
    const d: number | null = v.deltaDays;
    let verdict = '';
    if (d != null) {
      if (d > 0) verdict = `Delayed by ${days(d)}`;
      else if (d < 0) verdict = `Earlier by ${days(d)}`;
      else verdict = 'No change';
    } else if (!v.from && v.to) {
      verdict = 'Date set';
    } else if (v.from && !v.to) {
      verdict = 'Date cleared';
    }
    return { field: k === 'start' ? 'Start Date' : 'Finish Date', verdict, from: fmtDate(v.from), to: fmtDate(v.to) };
  }
  if (k === 'duration') {
    const d: number | null = v.deltaDays;
    let verdict = '';
    if (d != null) {
      if (d > 0) verdict = `Increased by ${days(d)}`;
      else if (d < 0) verdict = `Decreased by ${days(d)}`;
      else verdict = 'No change';
    }
    const fromStr = v.from != null ? `${v.from} days` : '';
    const toStr = v.to != null ? `${v.to} days` : '';
    return { field: 'Duration', verdict, from: fromStr, to: toStr };
  }
  if (k === 'percent') {
    const d: number | null = v.deltaPoints;
    let verdict = '';
    if (d != null) {
      if (d > 0) verdict = `Increased by ${Math.abs(d)} pts`;
      else if (d < 0) verdict = `Decreased by ${Math.abs(d)} pts`;
      else verdict = 'No change';
    }
    return {
      field: '% Complete',
      verdict,
      from: v.from != null ? `${v.from}%` : '',
      to: v.to != null ? `${v.to}%` : '',
    };
  }
  if (k === 'name') {
    return { field: 'Name', verdict: 'Renamed', from: String(v.from ?? ''), to: String(v.to ?? '') };
  }
  return { field: k, verdict: '', from: String(v.from ?? ''), to: String(v.to ?? '') };
}

export function exportGcScheduleDiffExcel(options: ExportOptions): void {
  const { meta, counts, changed, added, removed, fileName } = options;
  const wb = XLSX.utils.book_new();

  // Summary sheet
  const rows: any[][] = [
    ['GC Schedule — Version Comparison'],
    [],
    ['Project', meta.projectNumber ? `${meta.projectNumber} - ${meta.projectName}` : meta.projectName],
    ['From (older)', meta.fromVersionLabel],
    ['To (newer)', meta.toVersionLabel],
    ['Generated', format(new Date(), 'MMM d, yyyy h:mm a')],
  ];
  if (meta.generatedBy) rows.push(['Generated by', meta.generatedBy]);
  rows.push([], ['Changed', counts.changed], ['Added', counts.added], ['Removed', counts.removed]);
  const summarySheet = XLSX.utils.aoa_to_sheet(rows);
  summarySheet['!cols'] = [{ wch: 16 }, { wch: 65 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');

  // Changed sheet — one row per field change so the data is filterable
  const FIELD_ORDER = ['start', 'finish', 'duration', 'percent', 'name'];
  const changedHeader = ['Activity ID', 'Activity Name', 'Mechanical', 'Field', 'Change', 'From', 'To'];
  const changedData: any[][] = [changedHeader];
  for (const r of changed) {
    const keys = Object.keys(r.diffs).sort((a, b) => {
      const ai = FIELD_ORDER.indexOf(a);
      const bi = FIELD_ORDER.indexOf(b);
      return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
    });
    for (const k of keys) {
      const { field, verdict, from, to } = fieldVerdict(k, r.diffs[k]);
      changedData.push([
        r.activity_id ?? '',
        r.name ?? '',
        r.is_mechanical ? 'Yes' : 'No',
        field,
        verdict,
        from,
        to,
      ]);
    }
  }
  const changedSheet = XLSX.utils.aoa_to_sheet(changedData);
  changedSheet['!cols'] = [{ wch: 22 }, { wch: 48 }, { wch: 12 }, { wch: 14 }, { wch: 28 }, { wch: 16 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, changedSheet, 'Changed');

  // Added sheet
  const addedHeader = ['Activity ID', 'Activity Name', 'Mechanical', 'Start Date', 'Finish Date'];
  const addedData: any[][] = [
    addedHeader,
    ...added.map((r) => [
      r.activity_id ?? '',
      r.name ?? r.activity_name ?? '',
      r.is_mechanical ? 'Yes' : 'No',
      fmtDate(r.start_date),
      fmtDate(r.finish_date),
    ]),
  ];
  const addedSheet = XLSX.utils.aoa_to_sheet(addedData);
  addedSheet['!cols'] = [{ wch: 22 }, { wch: 55 }, { wch: 12 }, { wch: 14 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, addedSheet, 'Added');

  // Removed sheet
  const removedData: any[][] = [
    addedHeader,
    ...removed.map((r) => [
      r.activity_id ?? '',
      r.name ?? r.activity_name ?? '',
      r.is_mechanical ? 'Yes' : 'No',
      fmtDate(r.start_date),
      fmtDate(r.finish_date),
    ]),
  ];
  const removedSheet = XLSX.utils.aoa_to_sheet(removedData);
  removedSheet['!cols'] = [{ wch: 22 }, { wch: 55 }, { wch: 12 }, { wch: 14 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, removedSheet, 'Removed');

  XLSX.writeFile(wb, fileName);
}
